<a href="https://colab.research.google.com/github/ucfilho/ANN_2021_01/blob/main/Classification_ANN/ANN_faulty_diagnosis_catalysis_may_26_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# bibliotecas usadas
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

In [2]:
!git clone https://github.com/ucfilho/ANN_2021_01
%cd ANN_2021_01

fatal: destination path 'ANN_2021_01' already exists and is not an empty directory.
/content/ANN_2021_01


In [3]:
df=pd.read_csv("FAULT_DIAGNOSIS_maio_25_2017.txt",sep='\t')
print(df.head())

    TF    P  Flow  Y1  Y2  Y3
0  400  100   200   0   0   0
1  420  100   200   0   0   0
2  380  100   200   0   0   0
3  400  100   200   0   0   0
4  400   90   200   0   0   0


In [4]:
# separa os dados em normatizados e originais
X = df[['TF','P','Flow']]


In [5]:
y = df[['Y1','Y2','Y3']]
print(y)

    Y1  Y2  Y3
0    0   0   0
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
5    0   0   0
6    0   0   0
7    1   0   0
8    1   0   0
9    1   0   0
10   1   0   0
11   1   0   0
12   0   1   0
13   0   1   0
14   0   0   1
15   0   0   1


In [6]:
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.10, shuffle=True, random_state=3)

In [7]:
scaler_X = preprocessing.MinMaxScaler((-1,1)).fit(X)
# scaler_Y = preprocessing.MinMaxScaler((-1,1)).fit(y)

In [8]:
X_train = X.copy()
y_train = y.copy()
X_train = scaler_X.transform(X_train)
#y_train = scaler_Y.transform(y_train)

In [9]:
'''
X_train = scaler_X.transform(X_train)
X_test = scaler_X.transform(X_test)
y_train = scaler_Y.transform(y_train)
y_test = scaler_Y.transform(y_test)
'''

'\nX_train = scaler_X.transform(X_train)\nX_test = scaler_X.transform(X_test)\ny_train = scaler_Y.transform(y_train)\ny_test = scaler_Y.transform(y_test)\n'

In [10]:
# define a rede neural 
model = MLPClassifier(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(15),
                     random_state=1)

In [11]:
# treina a rede neural
model.fit(X_train, y_train)

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=15, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [12]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=model.predict(X_train)
# y_calc_test=model.predict(X_test)

In [13]:
y_train

Y1  Y2  Y3
0    0   0   0
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
5    0   0   0
6    0   0   0
7    1   0   0
8    1   0   0
9    1   0   0
10   1   0   0
11   1   0   0
12   0   1   0
13   0   1   0
14   0   0   1
15   0   0   1

In [14]:
y_calc_train

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [15]:
X_train

array([[-0.2       ,  1.        , -0.42857143],
       [-0.04      ,  1.        , -0.42857143],
       [-0.36      ,  1.        , -0.42857143],
       [-0.2       ,  1.        , -0.42857143],
       [-0.2       ,  0.        , -0.42857143],
       [-0.2       ,  1.        ,  0.14285714],
       [-0.2       ,  1.        , -1.        ],
       [-1.        ,  1.        , -0.42857143],
       [-0.8       ,  0.        , -0.42857143],
       [-0.6       , -1.        , -0.42857143],
       [-0.44      ,  1.        , -0.42857143],
       [-0.36      ,  1.        , -1.        ],
       [-0.2       ,  1.        ,  1.        ],
       [-0.2       ,  1.        ,  0.42857143],
       [ 1.        ,  1.        , -0.42857143],
       [ 0.8       ,  1.        , -1.        ]])

In [16]:
X_exemplo =pd.DataFrame({'TF':[300],'P':[90],'Flow':[300]})
# X_exemplo =pd.DataFrame({'TF':[400],'P':[100],'Flow':[200]})
X_exemplo =  scaler_X.transform(X_exemplo)
y_exemplo=model.predict(X_exemplo)
print(y_exemplo)

[[1 1 0]]
