<a href="https://colab.research.google.com/github/ucfilho/ANN_2021_01/blob/main/Optimization_Multi_layer_Perceptron_MLP/Otimiza_Polimero_ANN_maio_19_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# bibliotecas usadas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import optimize
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score 
from mpl_toolkits.mplot3d import Axes3D, axes3d
%matplotlib inline

In [2]:
# funcao normatiza dados
def Normatiza(x):
    strings=list(x)
    for i in strings:
        max_x=x[i].max()
        min_x=x[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=(x[i]-a)/b
    return x

In [3]:
# funcao retorna os dados a forma original
def Original(x,x_old):
    strings=list(x)
    for i in strings:
        max_x=x_old[i].max()
        min_x=x_old[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=x[i]*b+a
    return x

In [4]:
!git clone https://github.com/ucfilho/ANN_2021_01
%cd ANN_2021_01

fatal: destination path 'ANN_2021_01' already exists and is not an empty directory.
/content/ANN_2021_01


In [5]:
DAT=pd.read_csv("Polimero_maio_21_2015.txt",sep='\t')
print(DAT.head())

   Time     TC     Y  MI    MW
0  80.0  170.0  76.5  62  2940
1  80.0  180.0  77.0  60  3470
2  90.0  170.0  78.0  66  3680
3  90.0  180.0  79.5  59  3890
4  85.0  175.0  79.9  72  3480


In [6]:
# separa as colunas de interesse
Index=range(5)
Dat_Select=[]
Dat_Select=DAT.iloc[:,Index].copy()

In [7]:
# separa os dados em normatizados e originais
DAT_OLD=[]
DAT_OLD=Dat_Select.copy()
DAT=Normatiza(Dat_Select)

In [8]:
# separa os dados em treino e teste
train=DAT.sample(frac=1.0,random_state=None) # poderia ser frac=0.5? sim ou nao?
test=DAT.drop(train.index)

In [9]:
# obtem as variaveis independentes (treino e teste)
x_train=train.iloc[:,[0,1]]
x_test=test.iloc[:,[0,1]]
X_OLD=DAT_OLD.iloc[:,[0,1]]

In [10]:
# obtem as variaveis dependentes (treino e teste)
Index=[2,3,4]
y_train=train.iloc[:,Index]
y_test=test.iloc[:,Index]
Y_OLD=DAT_OLD.iloc[:,Index]
print(Y_OLD)
print(x_train)

       Y  MI    MW
0   76.5  62  2940
1   77.0  60  3470
2   78.0  66  3680
3   79.5  59  3890
4   79.9  72  3480
5   80.3  69  3200
6   80.0  68  3410
7   79.7  70  3290
8   79.8  71  3500
9   78.4  68  3360
10  75.6  71  3020
11  78.5  58  3630
12  77.0  57  3150
        Time        TC
3   0.707214  0.707214
1  -0.707214  0.707214
8   0.000000  0.000000
10 -1.000000  0.000000
4   0.000000  0.000000
6   0.000000  0.000000
0  -0.707214 -0.707214
9   1.000000  0.000000
5   0.000000  0.000000
2   0.707214 -0.707214
11  0.000000  1.000000
7   0.000000  0.000000
12  0.000000 -1.000000


In [11]:
# define a rede neural 
clf = MLPRegressor(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(6), 
                    random_state=1)

In [12]:
# treina a rede neural
clf.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPRegressor(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=6, learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=200,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=1, shuffle=True, solver='lbfgs',
             tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

In [13]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=clf.predict(x_train)
x_test=x_train
y_calc_test=clf.predict(x_test)
print(y_calc_train)
print(Y_OLD)

[[ 0.66161495 -0.73563706  0.9978445 ]
 [-0.40232803 -0.61551034  0.10438591]
 [ 0.84672034  0.7325246  -0.08307591]
 [-1.00018847  0.87224183 -0.82614598]
 [ 0.84672034  0.7325246  -0.08307591]
 [ 0.84672034  0.7325246  -0.08307591]
 [-0.61694881 -0.33433195 -1.00254881]
 [ 0.19186956  0.46796603 -0.11332535]
 [ 0.84672034  0.7325246  -0.08307591]
 [ 0.02148383  0.20079161  0.55636168]
 [ 0.2310253  -0.85125417  0.46323866]
 [ 0.84672034  0.7325246  -0.08307591]
 [-0.40305563 -1.00077048 -0.55530477]]
       Y  MI    MW
0   76.5  62  2940
1   77.0  60  3470
2   78.0  66  3680
3   79.5  59  3890
4   79.9  72  3480
5   80.3  69  3200
6   80.0  68  3410
7   79.7  70  3290
8   79.8  71  3500
9   78.4  68  3360
10  75.6  71  3020
11  78.5  58  3630
12  77.0  57  3150


In [14]:
# transforma a saida da rede em dataframe 
y_calc_train=pd.DataFrame(y_calc_train)
y_calc_test=pd.DataFrame(y_calc_test)
col_names=list(y_train)
y_calc_train.columns = col_names
y_calc_test.columns = col_names

In [15]:
# transforma dos dados calculados na forma original (nao normatizado)
y_calc_train=Original(y_calc_train,Y_OLD)
y_calc_test=Original(y_calc_test,Y_OLD)
print(y_calc_train)
print(Y_OLD)

            Y         MI           MW
0   79.504795  58.982722  3888.976135
1   77.004529  59.883672  3464.583307
2   79.939793  69.993935  3375.538943
3   75.599557  71.041814  3022.580660
4   79.939793  69.993935  3375.538943
5   79.939793  69.993935  3375.538943
6   76.500170  61.992510  2938.789315
7   78.400893  68.009745  3361.170458
8   79.939793  69.993935  3375.538943
9   78.000487  66.005937  3679.271796
10  78.492909  58.115594  3635.038363
11  79.939793  69.993935  3375.538943
12  77.002819  56.994221  3151.230235
       Y  MI    MW
0   76.5  62  2940
1   77.0  60  3470
2   78.0  66  3680
3   79.5  59  3890
4   79.9  72  3480
5   80.3  69  3200
6   80.0  68  3410
7   79.7  70  3290
8   79.8  71  3500
9   78.4  68  3360
10  75.6  71  3020
11  78.5  58  3630
12  77.0  57  3150


In [16]:
def MW_calc(x_test):
    global Y_OLD,clf
    y_calc_test=clf.predict(x_test)
    y_calc_test=Original(y_calc_test,Y_OLD)
    return y_calc_test['MW']
def MI_calc(x_test):
    global Y_OLD,clf
    y_calc_test=clf.predict(x_test)
    y_calc_test=Original(y_calc_test,Y_OLD)
    return y_calc_test['MI']
def Y_calc(x_test):
    global Y_OLD,clf
    y_calc_test=clf.predict(x_test)
    y_calc_test=Original(y_calc_test,Y_OLD)
    return y_calc_test['Y']

def Desirability(y,U,T,L):
    if y<L:
        d=0
    if (y>=L)&(y<=T):
        d=(y-L)/(T-L)
    if (y>=T)&(y<+U):
        d=(U-y)/(U-T)
    if (y>U):
        d=0
    return d

In [17]:
def function(x):
    Time=x[0]
    TC=x[1]
    MW=MW_calc(x)
    MI=MI_calc(x)
    Y=Y_calc(x)
    U=3890
    T=3400
    L=2940
    d1=Desirability(MW,U,T,L)
    U=68
    T=65
    L=62
    d2=Desirability(MI,U,T,L)
    U=80
    T=77.5
    L=75.6
    d3=Desirability(Y,U,T,L)
    fun = (-1)*(d1*d2*d3)**(1/3)
    return fun

In [19]:
bounds = [(-1, 1),(-1, 1)]

Condicoes = optimize.differential_evolution(function,bounds,
                                      init="latinhypercube", # obs: init="random"
                                      maxiter=100, popsize=50,recombination=0.5)

print(Condicoes)

RuntimeError: ignored

In [ ]:
print("hello world,I am evolving!!!")

PS: no planejamento de experimentos utilizando o Statistica -e-papers
Y=80
MI=65,044
MW=3586,1

tempo=86,65 e Temperatura=178,77