<a href="https://colab.research.google.com/github/ucfilho/ANN_2021_01/blob/main/Programacao_basica/Test_metrics_may_26_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score 

In [2]:
Y_true = [ 10, 20, 35, 40, 80]
A = [ 10, 20, 35, 40, 80]
B = []
for ai in A:
  B.append(ai*2)
C = [ 80, 35, 10, 20, 40]

In [3]:
df = pd.DataFrame({'True':Y_true, 'A':A, 'B':B, 'C':C})
print(df)

   True   A    B   C
0    10  10   20  80
1    20  20   40  35
2    35  35   70  10
3    40  40   80  20
4    80  80  160  40


In [4]:
y_obs= df['True']; y_calc=df['C']
R2=r2_score(y_obs,y_calc);print("R^2 teste=",R2)

R^2 teste= -1.6909722222222223


In [5]:
df_new = pd.DataFrame({'True':Y_true, 'A':A, 'B':B, 'C':C})
df_new = np.array(df_new)
print(df_new)

[[ 10  10  20  80]
 [ 20  20  40  35]
 [ 35  35  70  10]
 [ 40  40  80  20]
 [ 80  80 160  40]]


In [6]:
y_obs= df_new[:,0]; y_calc= df_new[:,1];
R2=r2_score(y_obs,y_calc);print("R^2 teste=",R2)

R^2 teste= 1.0
